# Numpyの初歩
**Numpy**は数値計算を行うための高速なライブラリです．  
コア部分がC言語やFortranで実装されており，多次元配列に対する演算をPython標準の関数よりも効率的に実行可能です．  
様々な機能がありますが，ここでは行列（ベクトル）の演算を簡易に行う方法を説明します．  

In [2]:
import numpy as np

## なぜnumpyで行列演算
標準のリストではベクトルの和や積を計算するのが面倒だからです．  
ex. 次の２つのベクトルの和を計算する  
<img src="https://latex.codecogs.com/png.image?\dpi{120}&space;\bg_white&space;a&space;=&space;\begin{pmatrix}1&space;\\2\end{pmatrix},~b&space;=&space;\begin{pmatrix}3&space;\\4\end{pmatrix}" title="\bg_white a = \begin{pmatrix}1 \\2\end{pmatrix},~b = \begin{pmatrix}3 \\4\end{pmatrix}" />

In [7]:
# forループで実装
a = [1, 2, 3]
b = [4, 5, 6]

ans = []
for i in range(3):
    ans.append(a[i] + b[i])

ans

[5, 7, 9]

In [8]:
# numpyで実装
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a + b

array([5, 7, 9])

このようにnumpyを使うと直感的な実装が可能になります．  

# 1次元配列
以下のように実体化する．  
```python
np.array(一次元リスト)
```

In [7]:
A = np.array([1, 2, 3,])
A

array([1, 2, 3])

In [8]:
B = np.array([4, 5, 6])
B

array([4, 5, 6])

## 和
`+`演算子を使う．想像通りの結果が得られる．  

In [9]:
A + B

array([5, 7, 9])

## 要素積
`*`演算子は要素ごとの積になる．  

In [10]:
A * B

array([ 4, 10, 18])

## 内積


In [16]:
2 * A

array([2, 4, 6])

# 2次元配列

In [17]:
C = np.array([
    [1, 2,],
    [3, 4]
])
C

array([[1, 2],
       [3, 4]])

In [22]:
D = np.array([[5, 6], [7, 8]])
D

array([[5, 6],
       [7, 8]])

In [23]:
C + D

array([[ 6,  8],
       [10, 12]])

In [19]:
C @ D

array([[19, 22],
       [43, 50]])

In [20]:
C * D

array([[ 5, 12],
       [21, 32]])

# 3次以上の多次元配列
省略