# Numpyの初歩
**Numpy**は数値計算を行うための高速なライブラリです．  
コア部分がC言語やFortranで実装されており，多次元配列に対する演算をPython標準の関数よりも効率的に実行可能です．  
様々な機能がありますが，ここでは行列（ベクトル）の演算を簡易に行うツールとしてnumpyを使う方法を説明します．  

In [11]:
import numpy as np

## なぜnumpyで行列演算
標準のリストではベクトルの和や積を計算するのが面倒だからです．  
ex. 次の２つの行列$a$と$b$の和を計算する  
$$
a = \begin{bmatrix}
1 & 2\\
3 & 4\\
\end{bmatrix},~~~b = \begin{bmatrix}
5 & 6\\
7 & 8\\
\end{bmatrix}
$$

In [12]:
# 標準のリストを使う
a = [[1, 2], [3, 4]]
b = [[5, 6], [7, 8]]

ans = [[], []]
for i in range(2):
    for j in range(2):
        ans[i].append(a[i][j] + b[i][j])

ans

[[6, 8], [10, 12]]

In [13]:
# numpyで実装
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

a + b

array([[ 6,  8],
       [10, 12]])

このようにnumpyを使うと直感的な実装が可能です．  

****
# 1次元配列
以下のように定義する．  
```python
np.array(一次元リスト)
```

In [14]:
A = np.array([1, 2, 3,])
A

array([1, 2, 3])

In [15]:
B = np.array([4, 5, 6])
B

array([4, 5, 6])

### 和
`+`演算子を使う．想像通りの結果が得られる．  

In [16]:
A + B

array([5, 7, 9])

### スカラー倍
`*`を使う

In [17]:
2 * A

array([2, 4, 6])

### 要素積
`*`演算子は要素ごとの積になる．  

In [18]:
A * B

array([ 4, 10, 18])

### 内積

In [19]:
np.dot(A, B)

32

****
# 2次元配列
1次元配列と同じように定義  

In [20]:
C = np.array([
    [1, 2],
    [3, 4]
])
C

array([[1, 2],
       [3, 4]])

In [21]:
D = np.array([
    [5, 6],
    [7, 8]
])
D

array([[5, 6],
       [7, 8]])

### 和

In [22]:
C + D

array([[ 6,  8],
       [10, 12]])

### スカラー倍

In [38]:
2 * C

array([[2, 4],
       [6, 8]])

### 行列の積
`@`を使うと行列の乗算になる．  

In [24]:
C @ D

array([[19, 22],
       [43, 50]])

### 要素積
`*`は要素ごとの積になる．  

In [25]:
C * D

array([[ 5, 12],
       [21, 32]])

## 行列と縦ベクトルの積
制御では縦ベクトルを使うことが多いです．  
こういうの⇓  
<img src="https://latex.codecogs.com/png.image?\dpi{120}&space;\bg_white&space;\dot{x}&space;=&space;Ax&space;=&space;\begin{pmatrix}a_{11}&space;&&space;a_{12}&space;\\a_{21}&space;&&space;a_{22}&space;\\\end{pmatrix}&space;\begin{pmatrix}x_1&space;\\x_2\end{pmatrix}&space;=&space;\begin{pmatrix}a_{11}x_1&space;&plus;&space;a_{12}x_2&space;\\a_{21}x_1&space;&plus;&space;a_{22}x_2\end{pmatrix}" title="\bg_white \dot{x} = Ax = \begin{pmatrix}a_{11} & a_{12} \\a_{21} & a_{22} \\\end{pmatrix} \begin{pmatrix}x_1 \\x_2\end{pmatrix} = \begin{pmatrix}a_{11}x_1 + a_{12}x_2 \\a_{21}x_1 + a_{22}x_2\end{pmatrix}" />  

Numpyの1次元配列には縦や横といった区別がないので，縦ベクトルは2次元配列で宣言する必要があります．  

In [26]:
A = np.array([
    [1, 2],
    [3, 4]
])
x = np.array([
    [5],
    [6]
])
A @ x

array([[17],
       [39]])

****
# 3次以上の多次元配列
画像処理でよく出てくる．ここでは省略．  

****
# よく使う関数（メソッド）
### .shape
ndarrayの形状を知りたいときに使う

In [27]:
C.shape

(2, 2)

$2\times2$の行列であることがわかる．  
### 転置行列
`.T`または`np.transpose()`

In [28]:
C.T

array([[1, 3],
       [2, 4]])

### 零行列
ゼロ埋めされた配列を作るときは以下の関数を使う．  
```python
np.zeros(形状)
```
２次元以上の場合，形状はタプルで指定する．  

In [29]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

次の関数も便利．
```python
np.zeros_like(A（ndarray）)
```
Aと同じ形のゼロ行列が作成される

In [31]:
C

array([[1, 2],
       [3, 4]])

In [32]:
np.zeros_like(C)

array([[0, 0],
       [0, 0]])

### 単位行列
`np.eye(n)`でn次元の単位行列を作成

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 形状変更
`.reshape`でndarrayの形状を変更する．  

In [34]:
C.reshape(1, 4)

array([[1, 2, 3, 4]])

In [35]:
np.reshape(C, (1, 4))

array([[1, 2, 3, 4]])

### 対角行列
```python
np.diag(対角要素のリスト)
```

In [36]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### ブロック行列
```python
np.block(ndarryのリスト)
```

In [40]:
np.block([
    [C, D],
    [D, C]
])

array([[1, 2, 5, 6],
       [3, 4, 7, 8],
       [5, 6, 1, 2],
       [7, 8, 3, 4]])