# numpy

In [6]:
import numpy as np

# 1次元配列

In [7]:
A = np.array([1, 2, 3,])
A

array([1, 2, 3])

In [8]:
B = np.array([4, 5, 6])
B

array([4, 5, 6])

In [9]:
A + B

array([5, 7, 9])

In [10]:
A * B

array([ 4, 10, 18])

In [16]:
2 * A

array([2, 4, 6])

# 2次元配列

In [17]:
C = np.array([
    [1, 2,],
    [3, 4]
])
C

array([[1, 2],
       [3, 4]])

In [22]:
D = np.array([[5, 6], [7, 8]])
D

array([[5, 6],
       [7, 8]])

In [23]:
C + D

array([[ 6,  8],
       [10, 12]])

In [19]:
C @ D

array([[19, 22],
       [43, 50]])

In [20]:
C * D

array([[ 5, 12],
       [21, 32]])

# 3次以上の多次元配列
省略