続き

In [1]:
import numpy as np

# インデクス，スライスによる部分選択

In [2]:
A = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
])
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

行番号と列番号を整数値で指定して取り出す．  
```python
ndarray[行番号, 列番号]
```

In [6]:
A[0, 0]

1

標準リストの二次元配列のような指定もできる．  

In [8]:
A[0][0]

1

In [11]:
A[-1][-1]

20

In [9]:
A[0, :]

array([1, 2, 3, 4, 5])

In [10]:
A[0, 1:3]

array([2, 3])

## 二次元配列のまま取り出す

In [13]:
A[:, 0:1]

array([[ 1],
       [ 6],
       [11],
       [16]])